<a href="https://colab.research.google.com/github/akshaypradheep/MATRICES_NCERT-12CH03/blob/master/MATRICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  # Basic Matrix

In [7]:
#make a matrix using numpy

import numpy as np
a_sample=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a_sample)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
#make a matrix using formula
# 3.2.1 Example 3 Construct a 3 × 2 matrix whose elements are given by a(ij)= 0.5*|i-3j|
#matrix start counting from A00 not A11
a32=np.fromfunction(lambda i, j: 0.5*abs((i - 3*j)), (3, 2), dtype=int)
print(a32)

[[0.  1.5]
 [0.5 1. ]
 [1.  0.5]]


In [29]:
#arrange a sequence as a matrix
x = np.arange(0,16,1).reshape((4,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Types of Matrices

In [15]:
## Types of Matrices
#A matrix is said to be a column matrix if it has only one column
column_matrix=np.array([[1],[2],[3],[4]])
print(column_matrix)

[[1]
 [2]
 [3]
 [4]]


In [16]:
#Row matrix
#A matrix is said to be a row matrix if it has only one row.
row_matrix=np.array([1,2,3,4,6])
print(row_matrix)

[1 2 3 4 6]


In [17]:
#Square matrix
#A matrix in which the number of rows are equal to the number of columns
square_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(square_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#Diagonal matrix
#is a sqare matric  diagonal matrix if all its non -
#diagonal elements are zero
x = np.arange(0,16,1).reshape((4,4)) #create a marix x
diagonal_matrix=np.diag(np.diag(x)) #diagonal vaules from x[] and create new diagonal matrix 
print(diagonal_matrix)

[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


In [44]:
#Scalar matrix
#A diagonal matrix is said to be a scalar matrix if its diagonal elements are equal
y=np.ones((5,5),dtype=int)*4
scalar_matrix=np.diag(np.diag(y))
print(scalar_matrix)

[[4 0 0 0 0]
 [0 4 0 0 0]
 [0 0 4 0 0]
 [0 0 0 4 0]
 [0 0 0 0 4]]


In [46]:
#Identity matrix
#square matrix  diagonal are all 1 and rest are all zero
z=np.ones((4,4),dtype=int)
identify_matrix=np.diag(np.diag(z))
print(identify_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [47]:
#Zero matrix
zero_matrix=np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
