<a href="https://colab.research.google.com/github/akshaypradheep/MATRICES_NCERT-12CH03/blob/master/MATRICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#make a matrix using numpy

import numpy as np
a_sample=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a_sample)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
#make a matrix using formula
# 3.2.1 Example 3 Construct a 3 × 2 matrix whose elements are given by a(ij)= 0.5*|i-3j|
#matrix start counting from A00 not A11
a32=np.fromfunction(lambda i, j: 0.5*abs((i - 3*j)), (3, 2), dtype=int)
print(a32)

[[0.  1.5]
 [0.5 1. ]
 [1.  0.5]]
